### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by Daraido** [noahgsolomon/brainrot.js#3]
I'm trying to generate using this, but it keeps saying my rate limit is exceeded for my openai account for the image generation, saying i need to have a rate limtit of at least 6 images per min but i only have 5 per min allowed i guess. Does this mean that I need to upgrade my usage tier from 1 to 2? Is there a way i can run this to where it only generates 5 of its images at a time? anyways, thank you for your help!

**Comment by noahgsolomon** [comment]
Yeah. That's a problem I should have mentioned... Because DALLE-3 rate limits are really strict. And each video typically has 7 dialog switches...

Either use google api for the google search images (change in localBuild.mjs and add necessary api keys), or write in the transcript.mjs prompt that it should only generate 5 dialog switches and not the typical 7

**Comment by Daraido** [comment]
Thanks! and them im getting a similar issue with: The model `ft:gpt-3.5-turbo-1106:personal` does not exist or you do not have access to it. (i removed a small code of characters that i hope wasnt anything identifying yikes)

**Comment by noahgsolomon** [comment]
Cool. Yeah I definitely recommend messing around with the code. It's mostly for running by polling from db with brainrotjs.com so it could use some tweaks for local

**Comment by Daraido** [comment]
Thanks for your help man! really cool thing you got here haha
