### ISSUE TITLE
Option to buy credits

### ISSUE THREAD

**Issue by Polygons1** [noahgsolomon/brainrot.js#8]
It will be cool for an option to buy a specific amount of credits (like 10 credits) in a one time purchase or a monthly ( / yearly) subscription

**Comment by noahgsolomon** [comment]
I agree that would be cool! I have the subscription up rn for 250 credits (25 vids / month) here: https://brainrotjs.com/pricing

**Comment by Polygons1** [comment]
also, how about using Stable Diffusion XL for the image generation? I think it will be better for running locally

**Comment by noahgsolomon** [comment]
totally. I currently have basically the exact same implementation for local as i do for brainrotjs.com so i haven't decoupled local vs brainrotjs.com (that's why in all the generate files there are checks if local or not). Once I go about doing that I'll definitely look into that!

If you want to give it a shot or know someone who might you'd be a goat if u dropped a pull request

**Comment by Polygons1** [comment]
try deploying it in https://portal.salad.com/ I've heard that it's really good
